name: Playwright test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Vérifier le code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # Installer Node.js
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      # Installer les navigateurs Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # Exécuter les tests avec le rapport HTML activé
      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      # Vérifier le dossier du rapport HTML
      - name: Check Playwright Report Directory
        run: ls -R playwright-report || echo "Report directory not found!"

      # Archiver les rapports HTML
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

  send-email:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Télécharger le rapport HTML
      - name: Download Playwright Report
        uses: actions/download-artifact@v3
        with:
          name: playwright-report

      # Vérifier le contenu du dossier téléchargé
      - name: List downloaded artifact files
        run: ls -R playwright-report || echo "No files in downloaded artifact!"

      # Localiser le fichier HTML
      - name: Locate HTML report
        run: find . -name "index.html" || echo "HTML report not found!"

      # Déplacer le rapport HTML si trouvé
      - name: Move HTML report
        run: mv playwright-report/index.html ./index.html || echo "No HTML report to move."

      # Vérifier que le fichier existe
      - name: Ensure HTML report exists
        run: test -f ./index.html || (echo "Report not found!" && exit 1)

      # Envoyer l'email avec le rapport HTML
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          # Configuration SMTP de l'expéditeur
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Playwright Test Report
          body: "Veuillez trouver en pièce jointe le rapport HTML généré après les tests."
          to: johnny.demarlier@gmail.com
          from: "automajohn01@gmail.com"
          attachments: ./index.html